export const techOptions = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'java', label: 'Java' },
  { value: 'c#', label: 'C#' },
  { value: 'c++', label: 'C++' },
  { value: 'react', label: 'React' },
  { value: 'python', label: 'Python' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'angular', label: 'Angular' },
  { value: 'vuejs', label: 'Vue.js' },
  { value: 'swift', label: 'Swift' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'golang', label: 'Go (Golang)' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'sass', label: 'Sass' },
  { value: 'docker', label: 'Docker' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'aws', label: 'AWS' },
  { value: 'azure', label: 'Azure' },
  { value: 'gcp', label: 'Google Cloud Platform' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'tensorflow', label: 'TensorFlow' },
  { value: 'pytorch', label: 'PyTorch' },
  { value: 'redis', label: 'Redis' },
  { value: 'bash', label: 'Bash' },
  { value: 'linux', label: 'Linux' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'django', label: 'Django' },
  { value: 'springboot', label: 'Spring Boot' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'express', label: 'Express.js' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'nestjs', label: 'NestJS' },
  { value: 'tailwindcss', label: 'Tailwind CSS' },
  { value: 'materialui', label: 'Material-UI' },
  { value: 'bootstrap', label: 'Bootstrap' },
  { value: 'webpack', label: 'Webpack' },
  { value: 'rollup', label: 'Rollup' },
  { value: 'vite', label: 'Vite' },
  { value: 'sequelize', label: 'Sequelize' },
  { value: 'prisma', label: 'Prisma' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'rust', label: 'Rust' },
];

export const destaqueOptions = [
  { value: 'umaEstrela', label: 'Uma estrela' },
  { value: 'duasEstrela', label: 'Duas estrelas' },
  { value: 'tresEstrela#', label: 'Três estrelas' },
];
